name: "Get and cache dependencies"
description: "Get the dependencies (via npm) and cache the dependencies"
runs:
  # this is a composite action and not a docker or js action 
  using: composite 
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash # you have to provide the shell where you want to execute the run