name: "Get and cache dependencies"
description: "Get the dependencies (via npm) and cache the dependencies"
inputs: # this is an input to the custom action
  caching: # this is an optional name
    description: Whether we want to cache or not
    required: false
    default: 'true'
runs:
  # this is a composite action and not a docker or js action 
  using: composite 
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      # if the cache-hit does not happen or we do not want to cache then install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash # you have to provide the shell where you want to execute the run